player:
    fullscreen: true
    monitor: -1
    onTop: false
    quitOnStop: true
    restartOnPlay: false
    subtitles:
        fixTiming: true
        font: 'Droid Sans'
        color: null
        bold: true
        italic: false
        spacing: 0
        backColor: null
        borderColor: null
        borderSize: null
        shadowColor: null
        shadowOffset: 0
        marginX: 25
        marginY: 46
server:
    port: 2019
    address: 0.0.0.0
    authenticate: null
    disableRunCommand: false