player:
    # Launch the player window in full screen
    fullscreen: true

    # Index of the monitor (0-32) where to open the player window
    monitor: null

    # Force the player window to always be on top
    onTop: false

    # If false, when stopping a video, the player window is kept open. If true, it is automatically closed
    quitOnStop: true

    # Determines if the player restarts everytime the user plays a new media when something was already playing
    restartOnPlay: false

    # Audio output drivers. More info here https://mpv.io/manual/stable/#audio-output-drivers
    audioOutput: null

    # Allows setting a custom audio output device (a custom display for example)
    # Run `mpv --audio-device=help` to get a list of the available audio devices for MPV
    audioDevice: null

    # Options related to the display of subtitles on the video player
    subtitles:
        fixTiming: true

        font: 'Droid Sans'
        color: null
        bold: true
        italic: false
        
        spacing: 0

        backColor: null
        borderColor: null
        borderSize: null

        shadowColor: null
        shadowOffset: 0

        marginX: 25
        marginY: 46

server:
    # The network port where the socket server will listen for incoming connections
    port: 2019

    # The network interface the server will bind to
    address: 0.0.0.0

    # Specify a password to authenticate clients. Null means no password
    authenticate: null

    # MPV provides a command that allows to run arbitrary system commands. In unprotected environments, 
    # this can present a security risk. Setting this value to true disables the command from socket requests
    disableRunCommand: false